import type { SourcePermission } from "../types";

export const defaultSources = [
  {
    id: "local-files",
    label: "Local files",
    sourceType: "local files",
    permissionLevel: 2,
    sensitivityAllowed: ["public", "internal", "confidential"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "User-provided local context only. The app does not scan or index files in the MVP.",
  },
  {
    id: "uploaded-documents",
    label: "Uploaded documents",
    sourceType: "uploaded documents",
    permissionLevel: 2,
    sensitivityAllowed: ["public", "internal", "confidential"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Documents intentionally supplied by the user for a task.",
  },
  {
    id: "web",
    label: "Web",
    sourceType: "web",
    permissionLevel: 1,
    sensitivityAllowed: ["public", "public-facing risk"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Reference source category only. The app does not perform live web search in the MVP.",
  },
  {
    id: "github",
    label: "GitHub",
    sourceType: "github",
    permissionLevel: 1,
    sensitivityAllowed: ["public", "internal"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Reference source category only. The app does not connect to GitHub.",
  },
  {
    id: "m365-sharepoint",
    label: "Microsoft 365 / SharePoint",
    sourceType: "m365 sharepoint",
    permissionLevel: 1,
    sensitivityAllowed: ["public", "internal"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Reference source category only. The app does not connect to Microsoft 365 or SharePoint.",
  },
  {
    id: "google-drive",
    label: "Google Drive",
    sourceType: "google drive",
    permissionLevel: 1,
    sensitivityAllowed: ["public", "internal"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Reference source category only. The app does not connect to Google Drive.",
  },
  {
    id: "personal-memory",
    label: "Personal memory",
    sourceType: "personal memory",
    permissionLevel: 2,
    sensitivityAllowed: ["public", "internal", "confidential"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "User-entered recollection or context, not an external memory connection.",
  },
  {
    id: "other-source",
    label: "Other source",
    sourceType: "other",
    permissionLevel: 0,
    sensitivityAllowed: ["public"],
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Placeholder for user-defined sources; starts at no access until configured.",
  },
] satisfies SourcePermission[];
