import type { ModelInventoryItem } from "../types";

export const defaultModels = [
  {
    id: "manual-human-review",
    label: "Human/manual review",
    provider: "User",
    tier: "human",
    enabled: true,
    localOnly: true,
    capabilityScores: {
      reasoning: 5,
      writing: 4,
      coding: 3,
      research: 3,
      packaging: 4,
    },
    maxPermissionLevel: 4,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Always available as the final approval route step. The app records the recommendation only.",
  },
  {
    id: "user-free-small-model",
    label: "User-configured free/small model",
    provider: "User inventory",
    tier: "small",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 2,
      writing: 3,
      coding: 2,
      research: 1,
      packaging: 2,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a free or lightweight assistant the user already has. No provider connection is made by the app.",
  },
  {
    id: "user-mid-synthesis-model",
    label: "User-configured mid-tier synthesis model",
    provider: "User inventory",
    tier: "mid",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 3,
      writing: 4,
      coding: 3,
      research: 2,
      packaging: 3,
    },
    maxPermissionLevel: 2,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a paid or capable assistant the user may already subscribe to. The app does not call it.",
  },
  {
    id: "user-frontier-quality-model",
    label: "User-configured frontier/quality model",
    provider: "User inventory",
    tier: "frontier",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 5,
      writing: 5,
      coding: 4,
      research: 3,
      packaging: 4,
    },
    maxPermissionLevel: 2,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents the user's highest-quality assistant option for expensive mistakes or high quality bars.",
  },
  {
    id: "user-research-tool",
    label: "User-configured research tool",
    provider: "User inventory",
    tier: "research",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 3,
      writing: 3,
      coding: 1,
      research: 5,
      packaging: 2,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a tool the user can consult for current facts or citations outside the app.",
  },
  {
    id: "user-artifact-tool",
    label: "User-configured artifact/packaging tool",
    provider: "User inventory",
    tier: "artifact",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 2,
      writing: 4,
      coding: 2,
      research: 1,
      packaging: 5,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a document, slide, table, or artifact tool the user already controls.",
  },
] satisfies ModelInventoryItem[];
