import type { ModelInventoryItem } from "../types";

export const defaultModels = [
  {
    id: "manual-human-review",
    label: "My own final review",
    provider: "You",
    tier: "human",
    enabled: true,
    localOnly: true,
    capabilityScores: {
      reasoning: 5,
      writing: 4,
      coding: 3,
      research: 3,
      packaging: 4,
    },
    maxPermissionLevel: 4,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Always available as the final approval step. The app records the recommendation only.",
  },
  {
    id: "user-free-small-model",
    label: "Free/basic AI assistant",
    provider: "Your tools",
    tier: "small",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 2,
      writing: 3,
      coding: 2,
      research: 1,
      packaging: 2,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a free or lightweight assistant you already have. No provider connection is made by the app.",
  },
  {
    id: "user-mid-synthesis-model",
    label: "Everyday paid assistant",
    provider: "Your tools",
    tier: "mid",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 3,
      writing: 4,
      coding: 3,
      research: 2,
      packaging: 3,
    },
    maxPermissionLevel: 2,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a paid or more capable assistant you may already subscribe to. The app does not call it.",
  },
  {
    id: "user-frontier-quality-model",
    label: "Strongest paid assistant",
    provider: "Your tools",
    tier: "frontier",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 5,
      writing: 5,
      coding: 4,
      research: 3,
      packaging: 4,
    },
    maxPermissionLevel: 2,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents your strongest assistant option for expensive mistakes or high quality bars.",
  },
  {
    id: "user-research-tool",
    label: "Research or web-answer tool",
    provider: "Your tools",
    tier: "research",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 3,
      writing: 3,
      coding: 1,
      research: 5,
      packaging: 2,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a tool you can consult for current facts or citations outside the app.",
  },
  {
    id: "user-artifact-tool",
    label: "Document, table, or slide helper",
    provider: "Your tools",
    tier: "artifact",
    enabled: true,
    localOnly: false,
    capabilityScores: {
      reasoning: 2,
      writing: 4,
      coding: 2,
      research: 1,
      packaging: 5,
    },
    maxPermissionLevel: 1,
    requiresCredentials: false,
    requiresExternalCall: false,
    notes: "Represents a document, slide, table, or packaging tool you already control.",
  },
] satisfies ModelInventoryItem[];
