import type { TaskTemplate } from "../types";

export const defaultTaskTemplates = [
  {
    id: "summarize-uploaded-docs",
    label: "Summarize uploaded documents",
    description: "Create a concise brief from documents the user intentionally supplies.",
    dmaicPhase: "analyze",
    lifecycleStage: "review",
    knowledgeWorkType: "synthesis",
    outputType: "brief",
    qualityBar: "standard",
    defaultSensitivityClass: "internal",
    requiresCurrentFacts: false,
    requiresCitations: true,
    publicFacing: false,
    costPreference: "balanced",
    energyPreference: "minimize",
    suggestedSourceIds: ["uploaded-documents"],
    requiresCredentials: false,
    requiresExternalCall: false,
  },
  {
    id: "draft-public-facing-copy",
    label: "Draft public-facing copy",
    description: "Prepare a draft that needs human approval before publication.",
    dmaicPhase: "improve",
    lifecycleStage: "draft",
    knowledgeWorkType: "writing",
    outputType: "draft",
    qualityBar: "high",
    defaultSensitivityClass: "public-facing risk",
    requiresCurrentFacts: false,
    requiresCitations: false,
    publicFacing: true,
    costPreference: "balanced",
    energyPreference: "balanced",
    suggestedSourceIds: ["personal-memory", "uploaded-documents"],
    requiresCredentials: false,
    requiresExternalCall: false,
  },
  {
    id: "research-current-facts",
    label: "Research current facts",
    description: "Plan a route that needs current evidence and citation-aware review.",
    dmaicPhase: "measure",
    lifecycleStage: "review",
    knowledgeWorkType: "research",
    outputType: "answer",
    qualityBar: "high",
    defaultSensitivityClass: "public",
    requiresCurrentFacts: true,
    requiresCitations: true,
    publicFacing: false,
    costPreference: "quality first",
    energyPreference: "balanced",
    suggestedSourceIds: ["web"],
    requiresCredentials: false,
    requiresExternalCall: false,
  },
  {
    id: "code-review-plan",
    label: "Create a code review plan",
    description: "Structure a review task without connecting to a repository.",
    dmaicPhase: "analyze",
    lifecycleStage: "review",
    knowledgeWorkType: "coding",
    outputType: "plan",
    qualityBar: "standard",
    defaultSensitivityClass: "internal",
    requiresCurrentFacts: false,
    requiresCitations: false,
    publicFacing: false,
    costPreference: "balanced",
    energyPreference: "balanced",
    suggestedSourceIds: ["github", "local-files"],
    requiresCredentials: false,
    requiresExternalCall: false,
  },
  {
    id: "package-route-card",
    label: "Package route card",
    description: "Prepare a route card or prompt package for local export.",
    dmaicPhase: "control",
    lifecycleStage: "approval",
    knowledgeWorkType: "packaging",
    outputType: "route card",
    qualityBar: "standard",
    defaultSensitivityClass: "internal",
    requiresCurrentFacts: false,
    requiresCitations: false,
    publicFacing: false,
    costPreference: "minimize",
    energyPreference: "minimize",
    suggestedSourceIds: ["personal-memory"],
    requiresCredentials: false,
    requiresExternalCall: false,
  },
] satisfies TaskTemplate[];
